import {
    Alert,
    Card,
    CardContent,
    Chip,
    Grid,
    Stack,
    Typography
} from "@mui/material";

import AutoAwesomeRoundedIcon from "@mui/icons-material/AutoAwesomeRounded";

import SectionCard from "../common/SectionCard";

import {
    InventoryProduct
} from "../../../../../types/ai/inventory";

interface Props {

    products: InventoryProduct[];

}

export default function InventoryRecommendations({

    products

}: Props) {

    const recommendations = products.filter(

        product =>

            product.recommendation !==

            "Maintain Current Stock"

    );

    return (

        <SectionCard

            title="AI Recommendations"

            subtitle="Smart inventory actions generated by AI"

        >

            {

                recommendations.length === 0 ?

                (

                    <Alert severity="success">

                        Inventory is healthy. No AI recommendations available.

                    </Alert>

                )

                :

                (

                    <Grid

                        container

                        spacing={3}

                    >

                        {

                            recommendations.map(

                                product => (

                                    <Grid

                                        key={

                                            product.productId

                                        }

                                        size={{

                                            xs:12,

                                            md:6,

                                            xl:4

                                        }}

                                    >

                                        <Card

                                            elevation={0}

                                            sx={{

                                                height:"100%",

                                                borderRadius:"20px",

                                                border:

                                                "1px solid rgba(184,155,115,.18)",

                                                boxShadow:

                                                "0 10px 25px rgba(0,0,0,.05)"

                                            }}

                                        >

                                            <CardContent>

                                                <Stack

                                                    direction="row"

                                                    justifyContent="space-between"

                                                    alignItems="center"

                                                    mb={2}

                                                >

                                                    <Typography

                                                        fontWeight={700}

                                                        color="#4A0E17"

                                                    >

                                                        {product.name}

                                                    </Typography>

                                                    <AutoAwesomeRoundedIcon

                                                        sx={{

                                                            color:"#B89B73"

                                                        }}

                                                    />

                                                </Stack>

                                                <Chip

                                                    label={

                                                        product.inventoryHealth

                                                    }

                                                    color={

                                                        product.inventoryHealth==="Healthy"

                                                        ?

                                                        "success"

                                                        :

                                                        product.inventoryHealth==="Low Stock"

                                                        ?

                                                        "warning"

                                                        :

                                                        "error"

                                                    }

                                                    size="small"

                                                />

                                                <Typography

                                                    mt={2}

                                                    fontWeight={600}

                                                >

                                                    Recommendation

                                                </Typography>

                                                <Typography

                                                    variant="body2"

                                                    color="text.secondary"

                                                >

                                                    {

                                                        product.recommendation

                                                    }

                                                </Typography>

                                                <Stack

                                                    spacing={1}

                                                    mt={3}

                                                >

                                                    <Typography

                                                        variant="caption"

                                                    >

                                                        Stock :

                                                        {" "}

                                                        {product.stock}

                                                    </Typography>

                                                    <Typography

                                                        variant="caption"

                                                    >

                                                        Turnover :

                                                        {" "}

                                                        {product.turnover}

                                                    </Typography>

                                                    <Typography

                                                        variant="caption"

                                                    >

                                                        Stockout Days :

                                                        {" "}

                                                        {

                                                            product.stockoutDays ??

                                                            "-"

                                                        }

                                                    </Typography>

                                                </Stack>

                                            </CardContent>

                                        </Card>

                                    </Grid>

                                )

                            )

                        }

                    </Grid>

                )

            }

        </SectionCard>

    );

}